repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black-jupyter
        name: Black (Jupyter)
        description:
          "Black code formatter with Jupyter notebook support"
        entry: black
        language: python
        minimum_pre_commit_version: '2.9.2'
        require_serial: true
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.21.0
    hooks:
      - id: cython-lint
        name: Cython Linter
        description: "Lint Cython files for style and syntax issues"
        files: \.(pyx|pxd|pxi)$
      - id: double-quote-cython-strings
        name: Double Quote Cython Strings
        description: "Enforce double quotes for strings in Cython files"
        files: \.(pyx|pxd|pxi)$

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        description: 'Static type checker for Python'
        entry: uv run mypy
        language: system
        'types_or': [ python, pyi ]
        pass_filenames: false
        args: [
            "--config-file=./mypy.ini", "."
        ]
        require_serial: true

  - repo: local
    hooks:
      - id: block-nonempty-env
        name: .env Blocker
        description: "Prevent committing non-empty .env files"
        entry: python ./hook_scripts/check_env.py
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:

      - id: end-of-file-fixer
        name: EoF Fixer
        description: "Ensure files end with a newline"
        entry: end-of-file-fixer
        exclude: ^(docs|scripts|coverage|MODELS)/

      - id: trailing-whitespace
        name: Trailing Whitespace Remover
        description: "Remove trailing whitespace"
        entry: trailing-whitespace-fixer
        exclude: ^(docs|scripts|coverage|MODELS)/
