def transform_arena_size(
    kind: str, n: int, p: int, order: int = 0, window: int = 0
) -> tuple[int, int]: ...
def regression_arena_size(
    kind: str, n: int, p: int, intercept: bool, n_alpha: int = 0, max_iter: int = 0
) -> tuple[int, int]: ...
def simulation_arena_size(
    order: int, n_state: int, n_var: int, n_exog: int, T: int, n_par: int
) -> tuple[int, int]: ...
def simulation_output_arena_size(
    order: int, n_var: int, n_exog: int, T: int, n_obs: int
) -> tuple[int, int]: ...
def filter_arena_size(
    kind: str, n_state: int, n_ctrl: int, n_exog: int, n_obs: int, T: int, n_par: int
) -> tuple[int, int]: ...
def diagnostic_arena_size(
    kind: str, n: int, p: int = 0, lags: int = 0
) -> tuple[int, int]: ...
