from enum import IntEnum

class MCStatus(IntEnum):
    _value_: int

    SUCCESS = ...
    POSTPROC_FAILED = ...

    DIAG_BAD_SHAPE = ...
    DIAG_LINALG = ...
    DIAG_UDEF_VARIANCE = ...
    DIAG_BAD_LAG = ...
    DIAG_INSUFFICIENT_SAMPLES = ...
    DIAG_ITERATIVE_NONCONVERGENCE = ...
    DIAG_BAD_PARAMETER = ...
    DIAG_FALLBACK = ...

    FILTER_SHAPE_MISMATCH = ...
    FILTER_MATRIX_CONDITION = ...

    BAD_ARG = ...
    NOT_RUN = ...

    TRANSFORM_BAD_ARG = ...
    TRANSFORM_OUT_OF_DOMAIN = ...

    REGRESSION_RANK_DEFICIENT = ...
    REGRESSION_NON_CONVERGENT = ...

    @property
    def message(self) -> str: ...
