from numpy import float64
from numpy.typing import NDArray

_F64 = NDArray[float64]

#: Status a kernel reports for an argument it is not defined on. The wrappers
#: raise ``ValueError`` rather than returning it.
BAD_ARG: int

def standardize_ax0(x: _F64, ddof: int = ...) -> _F64: ...
def log_transform(x: _F64, offset: float = ...) -> _F64: ...
def log_diff_transform(x: _F64, offset: float = ...) -> _F64: ...
def diff_transform(x: _F64, order: int = ...) -> _F64: ...
def rolling_mean(x: _F64, window: int = ...) -> _F64: ...
def rolling_var(x: _F64, window: int = ..., ddof: int = ...) -> _F64: ...
def rolling_std(x: _F64, window: int = ..., ddof: int = ...) -> _F64: ...
