from enum import IntEnum

class SolveStatus(IntEnum):
    _value_: int

    NEWTON_SINGULAR = ...
    NEWTON_NO_CONVERGE = ...

    QR = ...
    QZ = ...

    RANK_FAIL = ...
    INFINITE_ROOT = ...
    NO_STABLE_SOLUTION = ...
    STATIC_SINGULAR = ...
    SHOCK_SINGULAR = ...

    SECOND_ORDER_SINGULAR = ...
    SECOND_ORDER_RISK = ...
