from numpy import float64
from numpy.typing import NDArray

from typing import overload

_F64 = NDArray[float64]

# LOG TRANSFORM

@overload
def log_fwd(x: float64) -> float64: ...
@overload
def log_fwd(x: float) -> float64: ...
@overload
def log_fwd(x: _F64) -> _F64: ...
@overload
def log_inv(y: float64) -> float64: ...
@overload
def log_inv(y: float) -> float64: ...
@overload
def log_inv(y: _F64) -> _F64: ...
@overload
def log_grad_fwd(x: float64) -> float64: ...
@overload
def log_grad_fwd(x: float) -> float64: ...
@overload
def log_grad_fwd(x: _F64) -> _F64: ...
@overload
def log_grad_inv(y: float64) -> float64: ...
@overload
def log_grad_inv(y: float) -> float64: ...
@overload
def log_grad_inv(y: _F64) -> _F64: ...
@overload
def log_ldet_abs_jac_fwd(x: float64) -> float64: ...
@overload
def log_ldet_abs_jac_fwd(x: float) -> float64: ...
@overload
def log_ldet_abs_jac_fwd(x: _F64) -> _F64: ...
@overload
def log_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def log_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def log_ldet_abs_jac_inv(y: _F64) -> _F64: ...
@overload
def log_grad_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def log_grad_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def log_grad_ldet_abs_jac_inv(y: _F64) -> _F64: ...

# LOGIT TRANSFORM

@overload
def logit_fwd(x: float64) -> float64: ...
@overload
def logit_fwd(x: float) -> float64: ...
@overload
def logit_fwd(x: _F64) -> _F64: ...
@overload
def logit_inv(y: float64) -> float64: ...
@overload
def logit_inv(y: float) -> float64: ...
@overload
def logit_inv(y: _F64) -> _F64: ...
@overload
def logit_grad_fwd(x: float64) -> float64: ...
@overload
def logit_grad_fwd(x: float) -> float64: ...
@overload
def logit_grad_fwd(x: _F64) -> _F64: ...
@overload
def logit_grad_inv(y: float64) -> float64: ...
@overload
def logit_grad_inv(y: float) -> float64: ...
@overload
def logit_grad_inv(y: _F64) -> _F64: ...
@overload
def logit_ldet_abs_jac_fwd(x: float64) -> float64: ...
@overload
def logit_ldet_abs_jac_fwd(x: float) -> float64: ...
@overload
def logit_ldet_abs_jac_fwd(x: _F64) -> _F64: ...
@overload
def logit_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def logit_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def logit_ldet_abs_jac_inv(y: _F64) -> _F64: ...
@overload
def logit_grad_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def logit_grad_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def logit_grad_ldet_abs_jac_inv(y: _F64) -> _F64: ...

# PROBIT TRANSFORM

@overload
def probit_fwd(x: float64) -> float64: ...
@overload
def probit_fwd(x: float) -> float64: ...
@overload
def probit_fwd(x: _F64) -> _F64: ...
@overload
def probit_inv(y: float64) -> float64: ...
@overload
def probit_inv(y: float) -> float64: ...
@overload
def probit_inv(y: _F64) -> _F64: ...
@overload
def probit_grad_fwd(x: float64) -> float64: ...
@overload
def probit_grad_fwd(x: float) -> float64: ...
@overload
def probit_grad_fwd(x: _F64) -> _F64: ...
@overload
def probit_grad_inv(y: float64) -> float64: ...
@overload
def probit_grad_inv(y: float) -> float64: ...
@overload
def probit_grad_inv(y: _F64) -> _F64: ...
@overload
def probit_ldet_abs_jac_fwd(x: float64) -> float64: ...
@overload
def probit_ldet_abs_jac_fwd(x: float) -> float64: ...
@overload
def probit_ldet_abs_jac_fwd(x: _F64) -> _F64: ...
@overload
def probit_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def probit_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def probit_ldet_abs_jac_inv(y: _F64) -> _F64: ...
@overload
def probit_grad_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def probit_grad_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def probit_grad_ldet_abs_jac_inv(y: _F64) -> _F64: ...

# AFFINE LOGIT TRANSFORM

@overload
def aff_logit_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_grad_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_grad_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_grad_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_grad_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_grad_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_grad_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_ldet_abs_jac_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_ldet_abs_jac_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_ldet_abs_jac_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_ldet_abs_jac_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_logit_ldet_abs_jac_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_logit_ldet_abs_jac_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_logit_grad_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def aff_logit_grad_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def aff_logit_grad_ldet_abs_jac_inv(y: _F64) -> _F64: ...

# AFFINE PROBIT TRANSFORM

@overload
def aff_probit_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_grad_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_grad_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_grad_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_grad_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_grad_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_grad_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_ldet_abs_jac_fwd(x: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_ldet_abs_jac_fwd(x: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_ldet_abs_jac_fwd(x: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_ldet_abs_jac_inv(y: float64, low: float, high: float) -> float64: ...
@overload
def aff_probit_ldet_abs_jac_inv(y: float, low: float, high: float) -> float64: ...
@overload
def aff_probit_ldet_abs_jac_inv(y: _F64, low: float, high: float) -> _F64: ...
@overload
def aff_probit_grad_ldet_abs_jac_inv(y: float64) -> float64: ...
@overload
def aff_probit_grad_ldet_abs_jac_inv(y: float) -> float64: ...
@overload
def aff_probit_grad_ldet_abs_jac_inv(y: _F64) -> _F64: ...
